Controllers/ReforgeDevController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using SilentRoar.Data;
using SilentRoar.Models;

namespace SilentRoar.Controllers
{
  
    public class ReforgeDevController : Controller
    {
        private readonly AppDbContext _context;

        public ReforgeDevController(AppDbContext context)
        {
            _context = context;
        }
      // GET: ReforgeDev
        public async Task<IActionResult> Index()
        {
            var reforgeDevs = from s in _context.ReforgeDevs select s;
            reforgeDevs = reforgeDevs.OrderByDescending(s => s.ID);
            return View(await reforgeDevs.AsNoTracking().ToListAsync());
        }

        // GET: ReforgeDev/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reforgeDev = await _context.ReforgeDevs
                .FirstOrDefaultAsync(m => m.ID == id);
            if(reforgeDev == null)
            {
                return NotFound();
            }

            return View(reforgeDev);
        }

        // GET: ReforgeDev/Create
        //[Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
        
            return View();
        }

        // POST: ReforgeDev/Create
        // 创建Reforge 开发日志页面
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ReforgeDev reforgeDev)
        {
            if (ModelState.IsValid)
            {
                _context.Add(reforgeDev);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reforgeDev);
        }

        // GET: ReforgeDev/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reforgeDevLog = await _context.ReforgeDevs.FindAsync(id);
            if (reforgeDevLog == null)
            {
                return NotFound();
            }
            return View(reforgeDevLog);
        }

        // POST: ReforgeDev/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, ReforgeDev reforgeDevLog)
        {
            if (id != reforgeDevLog.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reforgeDevLog);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReforgeDevExists(reforgeDevLog.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details), new {id = reforgeDevLog.ID });
            }
            return View(reforgeDevLog);
        }

        // GET: ReforgeDev/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReforgeDev/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private bool ReforgeDevExists(int id)
        {
            return _context.ReforgeDevs.Any(e => e.ID == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SilentRoar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/prism.css" />
</head>
<body>
    <script src="~/js/prism.js"></script>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-black" asp-area="" asp-controller="Home" asp-action="Index">SilentRoar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 nav-pills">
                        <li class="nav-item dropdown">
                            <a class="nav-link active btn-info text-light dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Reforge Engine
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item text-black " asp-area="" asp-controller="ReforgeDev" asp-action="Index">日志</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SilentRoar - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>